### ISSUE TITLE
version 10 does not support Drupal 10

### ISSUE THREAD

**Issue by arderyp** [pantheon-systems/pantheon-enabler#20]
https://github.com/pantheon-systems/drupal-integrations/blob/10.x/composer.json#L7

And yet the pantheon instructions for migrating from drupal 9 to druapl 10 tell us to install version 10 of this package, which doesn't work: https://docs.pantheon.io/drupal-10#create-a-drupal-10-site

```
...
composer require --no-update pantheon-systems/drupal-integrations:^10
...
```

**Comment by greg-1-anderson** [comment]
@arderyp What error or problem are you seeing with drupal-integrations:^10 and Drupal 10? The line you highlighted causes a failure if the version of drupal/code is less than 10; this should work fine with Drupal 10.

**Comment by greg-1-anderson** [comment]
Just to be sure, I made a fresh clone of [drupal-10-composer-managed](https://github.com/pantheon-upstreams/drupal-10-composer-managed) and ran `composer install`, and confirmed that gave me version 10.0.0 of pantheon-systems/drupal-integrations

**Comment by arderyp** [comment]
Appologies @greg-1-anderson, I think I was misreading the error and now see what's going on.
