### ISSUE TITLE
settings.pantheon.php should only set $settings['config_sync_directory'] if it is unset

### ISSUE THREAD

**Issue by morvans** [pantheon-systems/pantheon-enabler#24]
Currently, the provided `settings.pantheon.php` overrides `$settings['config_sync_directory']` no matter what.

We're using the BLT-provided "settings.php parts" that configure the config directory according to `blt.yml` config file before `settings.pantheon.php` gets included.

I'd suggest we just wrap this with a `if (empty($settings['config_sync_directory']))`.

**Comment by jspellman814** [comment]
This fix has been included in tags `8.0.8`, `9.0.5` and `10.0.1`.
